name: GitHub Actions Injection Action

on:
    workflow_dispatch:
        inputs:
            injectable_input:
                description: 'The input to pass to the workflow'
                type: string
                required: true

jobs:
    injectable_job:
        uses: ./.github/workflows/github-actions-injection.yml
        with:
            injectable_input: "${{ github.event.inputs.injectable_input }}"