name: GitHub Actions Injection

on:
    workflow_call:
        inputs:
            injectable_input:
                description: 'The input to pass to the workflow'
                type: string
                required: true

jobs:
    injectable_job:
        runs-on: windows-latest
        steps:
            - name: Injected Step
              run: |
                echo "Injected Step: ${{ inputs.injectable_input }}"